all:
	pdflatex -interaction=nonstopmode main.tex
	pdflatex -interaction=nonstopmode main.tex

clean:
	rm -f *.aux *.log *.out *.toc *.synctex.gz ca1/*.aux midterm/*.aux ca2/*.aux endterm/*.aux frontmatter/*.aux
